# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09
Description: Tri Nguyen Duc - Exercise 3
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: udacity
      ImageId: 'ami-053b0d53c279acc90' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
      InstanceType: t2.micro
      Tags:
        - Key: "Project"
          Value: "udacity"
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0